VERSION: 2
_BASE_: "base_maskrcnn_r50_fpn.yaml"

DATASETS:
    TRAIN: ("sim+01_train_01",)
    TEST: ("SIM+01_val_02",)

MODEL:
    ROI_HEADS:
        NUM_CLASSES: 1
        BATCH_SIZE_PER_IMAGE: 256

    ANCHOR_GENERATOR:
        SIZES: [[16], [32], [64], [128], [256]]
        ASPECT_RATIOS: [[0.125, 0.25, 0.5, 1.0, 2.0, 4.0, 8.0]]

    RPN:
        PRE_NMS_TOPK_TRAIN: 4000
        PRE_NMS_TOPK_TEST: 2000
        POST_NMS_TOPK_TRAIN: 2000
        POST_NMS_TOPK_TEST: 1000

    ROI_MASK_HEAD:
        POOLER_RESOLUTION: 28

SOLVER:
    IMS_PER_BATCH: 2
    BASE_LR: 0.00025
    MAX_ITER: 7000
    STEPS: (4000, 5200)
    GAMMA: 0.1
    CHECKPOINT_PERIOD: 1000

TEST:
    EVAL_PERIOD: 1000


DATALOADER:
    NUM_WORKERS: 4

OUTPUT_DIR: "/mnt/c/Users/ooluwadare/maskrcnn_ctc/outputs/msc_maskrcnn_hero"